[features]
seeds = false
skip-lint = false
resolutions = true

[programs.localnet]
yield_protocol = "DjnbAUiRJ91rSftQqkgZZXqHiCZ7BpvYemxWhS6TwEaU"

[programs.devnet]
yield_protocol = "DjnbAUiRJ91rSftQqkgZZXqHiCZ7BpvYemxWhS6TwEaU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
